CREATE TABLE `member`(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
loginId CHAR(50) NOT NULL UNIQUE,
loginPw CHAR(200) NOT NULL,
`name` CHAR(50) NOT NULL,
`nickname` CHAR(50) NOT NULL,
email CHAR(50) NOT NULL UNIQUE,
phoneNumber CHAR(50) NOT NULL UNIQUE,
authLever TINYINT(1) NOT NULL DEFAULT 2 
COMMENT '0: 탈퇴 1: 정지: 2: 미인증 3: 인증 4: 관리자',
loginPwManage TINYINT(1) NOT NULL,
eamilAuth TINYINT(1) NOT NULL
);

CREATE TABLE cMessage(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
`body` TEXT NOT NULL,
senderMemberId INT(10) UNSIGNED NOT NULL,
receiverMemberId INT(10) UNSIGNED NOT NULL,
receiverDate DATETIME
);

CREATE TABLE board(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
memberId INT(10) UNSIGNED NOT NULL,
`code` CHAR(50) UNIQUE,
`name` CHAR(50) UNIQUE
);

CREATE TABLE article(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
title CHAR (100) NOT NULL,
`body` LONGTEXT NOT NULL,
memberId INT(10) NOT NULL,
boardId INT(10) NOT NULL,
hitsCount INT(10) NOT NULL DEFAULT 0
);

CREATE TABLE recommend(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
memberId INT(10) UNSIGNED NOT NULL,
relType CHAR(50) NOT NULL,
relId INT(10) UNSIGNED NOT NULL,
`point` TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE reply(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
memberId INT(10) UNSIGNED NOT NULL,
relType CHAR(50) NOT NULL,
relId INT(10) UNSIGNED NOT NULL,
delDate DATETIME,
delStatus TINYINT(1) NOT NULL
);

CREATE TABLE `file`(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
memberId INT(10) UNSIGNED NOT NULL,
originalFileName CHAR(100) NOT NULL,
fileExt CHAR(50) NOT NULL,
typeCode CHAR(20) NOT NULL,
type2Code CHAR(20) NOT NULL,
fileSize INT(10) UNSIGNED NOT NULL,
fileNo INT(10) UNSIGNED NOT NULL,
fileDir CHAR(20) NOT NULL,
fileExtTypeCode CHAR(20) NOT NULL,
fileExtType2Code CHAR(20) NOT NULL
);

CREATE TABLE chatRoom(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
title CHAR (100) NOT NULL,
memberId INT(10) UNSIGNED NOT NULL,
delDate DATETIME,
delStatus TINYINT(1) NOT NULL
);

CREATE TABLE chatRoomMsg(
id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
regDate DATETIME NOT NULL,
updateDate DATETIME NOT NULL,
chatRoomId INT(10) UNSIGNED NOT NULL,
memberId INT(10) UNSIGNED NOT NULL,
`body` TEXT NOT NULL,
delDate DATETIME,
delStatus TINYINT(1) NOT NULL
);